packages:
  - packages/*
  - integrations/*
  - playwright

preferWorkspacePackages: true

publicHoistPattern:
  - eslint
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200  # minutes (30 days)
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
- '@axonivy/*'
