// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Severity = ("INFO" | "WARNING" | "ERROR")
export type RestClientPropertyType = "STRING" | "PASSWORD";

export interface Webservices {
  boolean: boolean;
  editorFileContent: EditorFileContent;
  javaType: JavaType[];
  validationResult: ValidationResult[];
  webServiceContext: WebServiceContext;
  webServiceEditorData: WebServiceEditorData;
  webServiceSaveDataArgs: WebServiceSaveDataArgs;
  wsPropertyMeta: WsPropertyMeta[];
  [k: string]: unknown;
}
export interface EditorFileContent {
  content: string;
}
export interface JavaType {
  fullQualifiedName: string;
  packageName: string;
  simpleName: string;
}
export interface ValidationResult {
  message: string;
  path: string;
  severity: Severity;
}
export interface WebServiceContext {
  app: string;
  file: string;
  pmv: string;
}
export interface WebServiceEditorData {
  context: WebServiceContext;
  data: WebServiceData[];
  helpUrl: string;
  readonly: boolean;
}
export interface WebServiceData {
  codegen: WsCodegenOpts;
  description: string;
  features: string[];
  icon: string;
  id: string;
  name: string;
  properties: WsClientProperty[];
  service: WsService;
}
export interface WsCodegenOpts {
  namespaceMappings: MapStringString;
  underscoreNames: boolean;
  wsdlUrl: string;
}
export interface MapStringString {
  [k: string]: string;
}
export interface WsClientProperty {
  key: string;
  type: RestClientPropertyType;
  value: string;
}
export interface WsService {
  ports: WsPort[];
  serviceClass: string;
}
export interface WsPort {
  fallbackLocationUris: string[];
  locationUri: string;
  name: string;
}
export interface WebServiceSaveDataArgs {
  context: WebServiceContext;
  data: WebServiceData[];
  directSave: boolean;
}
export interface WsPropertyMeta {
  description: string;
  property: string;
}
