// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WebServicePropertyType = ("STRING" | "PASSWORD" | "PATH")
export type Severity = 'INFO' | 'WARNING' | 'ERROR';

export interface Webservices {
  boolean: boolean;
  editorFileContent: EditorFileContent;
  javaType: JavaType[];
  webServiceContext: WebServiceContext;
  webServiceEditorData: WebServiceEditorData;
  webServiceSaveDataArgs: WebServiceSaveDataArgs;
  webServicePropertyMeta: WebServicePropertyMeta[];
  validationResult: ValidationResult[];
  [k: string]: unknown;
}
export interface EditorFileContent {
  content: string;
}
export interface JavaType {
  fullQualifiedName: string;
  packageName: string;
  simpleName: string;
}
export interface WebServiceContext {
  app: string;
  file: string;
  pmv: string;
}
export interface WebServiceEditorData {
  context: WebServiceContext;
  data: WebServiceData[];
  helpUrl: string;
  readonly: boolean;
}
export interface WebServiceData {
  description: string;
  features: string[];
  icon: string;
  id: string;
  name: string;
  openApi: WebServiceOpenApi;
  properties: WebServiceProperty[];
  uri: string;
}
export interface WebServiceOpenApi {
  namespace: string;
  resolveFully: boolean;
  spec: string;
}
export interface WebServiceProperty {
  key: string;
  type: WebServicePropertyType;
  value: string;
}
export interface WebServiceSaveDataArgs {
  context: WebServiceContext;
  data: WebServiceData[];
  directSave: boolean;
}
export interface WebServicePropertyMeta {
  description: string;
  property: string;
}
export interface ValidationResult {
  message: string;
  path: string;
  severity: Severity;
}
